### ISSUE TITLE
fails to build from source with golang 1.6 beta 2

### ISSUE THREAD

**Issue by xnox** [hashicorp/consul-migrate#1]
```
=== RUN   TestMigrator_migrate
--- FAIL: TestMigrator_migrate (0.01s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
    panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 24 [running]:
testing.tRunner.func1(0xc82009c630)
    /usr/lib/go/src/testing/testing.go:467 +0x192
github.com/armon/gomdb.(*Txn).Get(0xc820084298, 0x2, 0xc82019a108, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /«PKGBUILDDIR»/obj-x86_64-linux-gnu/src/github.com/armon/gomdb/txn.go:140 +0x151
github.com/hashicorp/raft-mdb.(*MDBStore).GetLog(0xc8200dfbe0, 0x1, 0xc82006dec0, 0x0, 0x0)
    /«PKGBUILDDIR»/obj-x86_64-linux-gnu/src/github.com/hashicorp/raft-mdb/mdb_store.go:189 +0x307
github.com/hashicorp/consul-migrate/migrator.(*Migrator).migrateLogStore(0xc82006a2a0, 0x0, 0x0)
    /«PKGBUILDDIR»/obj-x86_64-linux-gnu/src/github.com/hashicorp/consul-migrate/migrator/migrator.go:161 +0x193
github.com/hashicorp/consul-migrate/migrator.(*Migrator).Migrate(0xc82006a2a0, 0x0, 0x0, 0x0)
    /«PKGBUILDDIR»/obj-x86_64-linux-gnu/src/github.com/hashicorp/consul-migrate/migrator/migrator.go:203 +0x5be
github.com/hashicorp/consul-migrate/migrator.TestMigrator_migrate(0xc82009c630)
    /«PKGBUILDDIR»/obj-x86_64-linux-gnu/src/github.com/hashicorp/consul-migrate/migrator/migrator_test.go:129 +0x1d8
testing.tRunner(0xc82009c630, 0xd97870)
    /usr/lib/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
    /usr/lib/go/src/testing/testing.go:582 +0x892
FAIL    github.com/hashicorp/consul-migrate/migrator    0.018s
```

**Comment by armon** [comment]
I'm closing as this looks like an issue with Go 1.6 beta handling of cgo. Please re-open if this is an issue with 1.6 final.

**Comment by xnox** [comment]
No, this is not an issue with Go 1.6. It is an intentional upstream change. It's a change in the specification, which no longer allows Go pointer to Go pointer. https://github.com/golang/go/issues/12416

**Comment by armon** [comment]
@xnox I see. Consul 0.6 has deprecated use of cgo and is moving to Go 1.6. Older consul versions used cgo and this migrator is a one time utility to convert data from versions 0.5.0 and older into the 0.6.0 format. That said, I would use our pre compiled binaries or Go 1.5, or submit a PR to make this 1.6 compatible.

**Comment by onlyjob** [comment]
I hope now would be a good time to fix this problem.
Due to this [FTBFS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818121) we have a problem in all packages depending on _consul-migrate_ In Debian...

**Comment by armon** [comment]
@onlyjob The package can be deprecated at this point, as it is not necessary for the last 4 releases of Consul.

**Comment by onlyjob** [comment]
Good to know, thanks.
